name: AfterReadme

on:
  workflow_call:
    inputs:
      username:
        description: 'The GitHub username to calculate the contribution streak for.'
        required: true
        type: string
      commit_message:
        description: 'The commit message to use when updating the README.'
        required: false
        type: string
        default: 'chore(bot): Update README'

    secrets:
      GH_PAT:
        description: 'A Personal Access Token (PAT) with repo scope to commit changes.'
        required: true

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with Streak Stats
        env:
          USERNAME: ${{ inputs.username }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          chmod +x .github/workflows/AfterReadme/get-daily-streak.sh
          
          bash .github/workflows/AfterReadme/get-daily-streak.sh

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.commit_message }}
          file_pattern: README.md
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"