name: AfterReadme

on:
  workflow_call:
    inputs:
      username:
        description: 'GitHub username'
        required: true
        type: string
      commit_message:
        description: 'Commit message e.g chore(bot): Update README'
        required: false
        type: string
        default: 'chore(bot): Update README'

    secrets:
      GH_PAT:
        description: 'Personal Access Token (PAT)'
        required: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone AfterReadme
        run: |
          git clone https://github.com/username/AfterReadme.git
          ls AfterReadme

      - name: Update README
        env:
          USERNAME: ${{ inputs.username }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          chmod +x AfterReadme/readme-updater.sh
          
          bash AfterReadme/readme-updater.sh

      - name: Remove cloned AfterReadme
        run: rm -rf AfterReadme

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.commit_message }}
          file_pattern: README.md
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"