name: Update README

on:
  #push:
  # branches:
  #   - main
  #schedule:
  # - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-after-readme-workflow:
    uses: IMOitself/AfterReadme/.github/workflows/after-readme.yml@443c6586a5ec6f12af6e45fcd0197d37fb2d0fab
    with:
      username: 'IMOitself'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
